version: 0.0
os: linux
files:
  - source:  /
    destination: /tmp/rigo-deploy

file_exists_behavior: OVERWRITE

permissions:


hooks:
  ApplicationStop:
    - location: scripts/codedeploy/appstop.sh
      runas: rigo_svc
  ApplicationStart:
    - location: scripts/codedeploy/appstart.sh
      runas: rigo_svc
