version: 0.0
os: linux
files:
  - source:  /
    destination: /tmp/rigo-deploy

file_exists_behavior: OVERWRITE

hooks:
  ApplicationStop:
    - location: scripts/codedeploy/appstop.sh
      timeout: 120
      runas: rigo_svc

  BeforeInstall:
    - location: scripts/codedeploy/replace.sh
      timeout: 60
      runas: rigo_svc

  ApplicationStart:
    - location: scripts/codedeploy/appstart.sh
      timeout: 120
      runas: rigo_svc
