version: 0.0
os: linux
files:
  - source:  /
    destination: /tmp/rigo-deploy

file_exists_behavior: OVERWRITE

hooks:
  ApplicationStop:
    - location: appstop.sh
      timeout: 60
      runas: rigo_svc

  AfterInstall:
    - location: replace.sh
      timeout: 30
      runas: rigo_svc

  ApplicationStart:
    - location: appstart.sh
      timeout: 30
      runas: rigo_svc

  ValidateService:
    - location: validate_svc.sh
      timeout: 30
      runas: rigo_svc