version: 0.2

phases:
  pre_build:
    commands:
      - echo Build started on $(date)

  build:
    commands:
      - echo Building the binary image...
      - go version
      - go mod tidy
      - make

  post_build:
    commands:
      - echo Build completed on $(date)
      - chmod +x scripts/deploy/aws/*.sh
      - build/linux/arcanus --home ./build/.arcanus --chain_id demonet --holders 10 --priv_validator_secret '1'
      - pwd

artifacts:
  files:
    - appspec.yml
    - build/linux/*
    - scripts/deploy/aws/*
  discard-paths: yes
  secondary-artifacts:
    artifact1:
      files:
        - .arcanus/**/*
      base-directory: build